#!/bin/bash

# Configuration
MOD_ID="ancestral_arcane"
SRC_BASE="src/main/resources/assets/$MOD_ID/arcane items"
DEST_BASE="src/main/resources/assets/$MOD_ID"
WIKI_DEST="../Ancestral-Arcane.wiki/imgs"

echo "======================================"
echo "Updating $MOD_ID textures..."
echo "======================================"

# Ensure destination directories exist
mkdir -p "$DEST_BASE/textures/block"
mkdir -p "$DEST_BASE/textures/item"
mkdir -p "$DEST_BASE/textures/gui/arcane_table"

# 1. Blocks & GUI
echo "Copying blocks and GUI textures..."
find "$SRC_BASE/arcane_table" -maxdepth 1 -type f -name "*.png" | while read -r file; do
    filename=$(basename "$file")
    if [[ "$filename" == arcane_table_* ]]; then
        cp "$file" "$DEST_BASE/textures/block/$filename"
    else
        cp "$file" "$DEST_BASE/textures/gui/arcane_table/$filename"
    fi
done

# 2. Simple Items (Grimoires & Scrolls, Runes)
echo "Copying simple item textures..."
for dir in "grimoire and scroll" "runes"; do
    if [ -d "$SRC_BASE/$dir" ]; then
        find "$SRC_BASE/$dir" -maxdepth 1 -type f -name "*.png" | while read -r file; do
            filename=$(basename "$file")
            item_id="${filename%.png}"
            
            # Handle special grimoire names based on Python script
            case "$item_id" in
                grimoire_1) item_id="grimoire_t1" ;;
                grimoire_2) item_id="grimoire_t2" ;;
                grimoire_3) item_id="grimoire_t3" ;;
                grimoire_4) item_id="grimoire_t4" ;;
                grimoire_5) item_id="grimoire_t5" ;;
                grimoire_forgoten) item_id="forgotten_magicbook" ;;
            esac
            
            cp "$file" "$DEST_BASE/textures/item/${item_id}.png"
            cp "$file" "$WIKI_DEST/${item_id}.png"
        done
    fi
done

# 3. Wands
echo "Generating and Copying wand textures..."
if [ -d "$SRC_BASE/wands_muckups" ]; then
    # Run wand generation script
    cd "$SRC_BASE/wands_muckups" || exit
    ./generate_wands.sh
    cd - > /dev/null || exit
fi

if [ -d "$SRC_BASE/wands_cast" ]; then
    find "$SRC_BASE/wands_cast" -maxdepth 1 -type f -name "*.png" | while read -r file; do
        cp "$file" "$DEST_BASE/textures/item/$(basename "$file")"
        cp "$file" "$WIKI_DEST/$(basename "$file")"
    done
fi

# Sync all items generated by wands script to wiki
echo "Syncing generated item textures to Wiki..."
find "$DEST_BASE/textures/item" -maxdepth 1 -type f -name "*.png" | while read -r file; do
    cp "$file" "$WIKI_DEST/$(basename "$file")"
done

echo "======================================"
echo "Texture update complete!"
echo "======================================"
